import { Injectable, Logger } from '@nestjs/common';
import OpenAI from 'openai';
import axios from 'axios';
import { DynamicConfigService } from '../settings/settings.service';

@Injectable()
export class ClusterService {
  private readonly logger = new Logger(ClusterService.name);

  constructor(private readonly dynamicConfig: DynamicConfigService) {}

  async generateBackgroundImage(backgroundScene: string): Promise<Buffer> {
    const apiKey = await this.dynamicConfig.get('cluster_api_key', 'CLUSTER_API_KEY');
    const model = await this.dynamicConfig.get('cluster_model', 'CLUSTER_MODEL', 'flux-2-max');
    const size = await this.dynamicConfig.get('cluster_size', 'CLUSTER_SIZE', '1024x1024') as '1024x1024';

    if (!apiKey || apiKey.trim() === '' || apiKey === 'your_cluster_api_key_here') {
      throw new Error('ClusterProtocol API Key is not configured. Please set a valid CLUSTER_API_KEY in the dashboard Settings or .env file.');
    }

    const client = new OpenAI({
      baseURL: 'https://api.clusterprotocol.ai/v1',
      apiKey,
    });

    // IMPORTANT: Ask for ONLY a background photo — absolutely NO text, NO words,
    // NO letters, NO numbers, NO signs, NO labels in the image.
    // Text will be added programmatically by Sharp.
    const imagePrompt = `${backgroundScene}. \
High quality cinematic photograph. \
Absolutely NO text, NO words, NO letters, NO numbers, NO signs, NO watermarks, \
NO overlays anywhere in the image. \
Clean background only — the image will have text added on top separately. \
Dramatic lighting, professional photography, ultra sharp, 1:1 square format.`;

    let lastError: any;

    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        this.logger.log(`Generating background image via ClusterProtocol (attempt ${attempt}/3)...`);

        const response = await client.images.generate({
          model,
          prompt: imagePrompt,
          n: 1,
          size,
        });

        const imageUrl = response.data?.[0]?.url;
        const b64 = response.data?.[0]?.b64_json;

        if (imageUrl) {
          this.logger.log(`Background image URL received: ${imageUrl}. Downloading...`);
          const imgResponse = await axios.get(imageUrl, { responseType: 'arraybuffer' });
          return Buffer.from(imgResponse.data);
        }

        if (b64) {
          this.logger.log('Background image received as base64.');
          return Buffer.from(b64, 'base64');
        }

        throw new Error('ClusterProtocol returned neither image URL nor base64 data');

      } catch (error: any) {
        lastError = error;
        this.logger.warn(`Background generation attempt ${attempt} failed: ${error.message}`);
        if (attempt < 3) await new Promise(r => setTimeout(r, 3000));
      }
    }

    throw new Error(`ClusterProtocol image generation failed after 3 attempts: ${lastError?.message || 'Unknown error'}`);
  }

  private async uploadToImgBB(base64Image: string): Promise<string> {
    const imgbbApiKey = await this.dynamicConfig.get('imgbb_api_key', 'IMGBB_API_KEY');
    if (!imgbbApiKey) {
      throw new Error('IMGBB_API_KEY is not configured. ImgBB is required to host the base64 image generated by ClusterProtocol.');
    }

    const params = new URLSearchParams();
    params.append('image', base64Image);

    const response = await axios.post<{ data: { url: string } }>(
      `https://api.imgbb.com/1/upload?key=${imgbbApiKey}`,
      params,
      {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        timeout: 30000,
      },
    );

    const url = response.data?.data?.url;
    if (!url) {
      throw new Error('ImgBB did not return a public URL in response');
    }

    return url;
  }
}
